export const GET_ITEM_DETAIL = "GET_ITEM_DETAIL";
export const IS_WISHED = "IS_WISHED";
export const SET_WISHED = "SET_WISHED";
export const CANCEL_WISHED = "CANCEL_WISHED";

export const GET_ITEM_DETAIL_ACTION = {
  REQUEST : "GET_ITEM_DETAIL_REQUEST",
  SUCCESS : "GET_ITEM_DETAIL_SUCCESS",
  FAILURE : "GET_ITEM_DETAIL_FAILURE",
};

export const IS_WISHED_ACTION = {
    REQUEST : "IS_WISHED_REQUEST",
    SUCCESS : "IS_WISHED_SUCCESS",
    FAILURE : "IS_WISHED_FAILURE",

};

export const SET_WISHED_ACTION = {
    REQUEST : "SET_WISHED_REQUEST",
    SUCCESS : "SET_WISHED_SUCCESS",
    FAILURE : "SET_WISHED_FAILURE",

};

export const CANCEL_WISHED_ACTION  = {
    REQUEST : "CANCEL_WISHED_REQUEST",
    SUCCESS : "CANCEL_WISHED_SUCCESS",
    FAILURE : "CANCEL_WISHED_FAILURE",
};

