

export const MY_PAGE_GET_COUNT = {
    REQUEST : MY_PAGE_GET_COUNT_REQUEST,
    SUCCESS : MY_PAGE_GET_COUNT_SUCCESS,
    FAILURE : MY_PAGE_GET_COUNT_FAILURE,
};

export const MY_PAGE_ACCOUNT = {
    REQUEST : MY_PAGE_GET_ACCOUNT_REQUEST,
    SUCCESS : MY_PAGE_GET_ACCOUNT_SUCCESS,
    FAILURE : MY_PAGE_GET_ACCOUNT_FAILURE,
};




