export const MY_PAGE_COUNT = "MY_PAGE_COUNT";
export const MY_PAGE_GET_ACCOUNT = "MY_PAGE_GET_ACCOUNT";
export const MY_PAGE_COUNT_ACTION = {
    REQUEST : `${MY_PAGE_COUNT}_REQUEST`,
    SUCCESS : `${MY_PAGE_COUNT}_SUCCESS`,
    FAILURE : `${MY_PAGE_COUNT}_FAILURE`,
};

export const MY_PAGE_ACCOUNT_ACTION = {
    REQUEST : `${MY_PAGE_GET_ACCOUNT}_REQUEST`,
    SUCCESS : `${MY_PAGE_GET_ACCOUNT}_SUCCESS`,
    FAILURE : `${MY_PAGE_GET_ACCOUNT}_FAILURE`,
};




