import key_mirror from 'key-mirror';

export const GET_NOTE_ITEM = {
    REQUEST : "GET_NOTE_ITEM_REQUEST",
    SUCCESS : "GET_NOTE_ITEM_SUCCESS",
    FAILURE : "GET_NOTE_ITEM_FAILURE",
};

export const CREATE_NOTE_ITEM = {
    REQUEST : "CREATE_NOTE_ITEM_REQUEST",
    SUCCESS : "CREATE_NOTE_ITEM_SUCCESS",
    FAILURE : "CREATE_NOTE_ITEM_FAILURE",
};

export const UPDATE_NOTE_ITEM = {
    REQUEST : "UPDATE_NOTE_ITEM_REQUEST",
    SUCCESS : "UPDATE_NOTE_ITEM_SUCCESS",
    FAILURE : "UPDATE_NOTE_ITEM_FAILURE",
};

export const REMOVE_NOTE_ITEM = {
    REQUEST : "REMOVE_NOTE_ITEM_REQUEST",
    SUCCESS : "REMOVE_NOTE_ITEM_SUCCESS",
    FAILURE : "REMOVE_NOTE_ITEM_FAILURE",
};
