import key_mirror from 'key-mirror';
/*
    SearchType

 */
export const SEARCH_PRODUCT = "SEARCH_PRODUCT";
export const SUBMIT_SEARCH_RESULT = "SUBMIT_SEARCH_RESULT";

export const SEARCH_PRODUCT_ACTION = {
    REQUEST : `${SEARCH_PRODUCT}_REQUEST`,
    SUCCESS : `${SEARCH_PRODUCT}_SUCCESS`,
    FAILURE : `${SEARCH_PRODUCT}_FAILURE`,
};
export const SUBMIT_SEARCH_RESULT_ACTION={
    REQUEST : `${SUBMIT_SEARCH_RESULT}_REQUEST`,
    SUCCESS : `${SUBMIT_SEARCH_RESULT}_SUCCESS`,
    FAILURE : `${SUBMIT_SEARCH_RESULT}_FAILURE`,
};



